### ISSUE TITLE
困った

### ISSUE THREAD

**Issue by 2ndwave-yamamoto** [2ndwave-yamamoto/tutorial-app#1]
### vagrantfile
config.vm.network "public_network", ip: "192.168.0.165"の追加
```
Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.synced_folder "~/projects/tutorial/tutorial-app", "/home/vagrant/tutorial-app"
  #config.vm.network "private_network", ip: "192.168.33.10"
  config.vm.network "public_network", ip: "192.168.0.165"
  # 追記部分
  config.vm.provision "file", source: "~/.ssh/id_ed25519.pub", destination: "~/.ssh/id_ed25519.pub"
  config.vm.provision "shell", inline: <<-SHELL
    cat /home/vagrant/.ssh/id_ed25519.pub >> /home/vagrant/.ssh/authorized_keys
  SHELL
  # ポートフォワード設定
  config.vm.network "forwarded_port", guest: 80, host: 8080
end
```

### database.yml
host: 192.168.33.10 →　127.0.0.1に変更
```
development:
  <<: *default
  host: 127.0.0.1
  database: tutorial_app_development
  username: vagrant
  password: developmentPassword4!
```
